# Generated by Django 4.2.16 on 2024-10-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
